name: CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: app
        run: npm ci

      - name: Audit dependencies
        working-directory: app
        run: npm audit --audit-level=high

      - name: Scan secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: auto

      - name: Build Docker image
        run: docker build -t estudo-supabase ./app

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: estudo-supabase:latest
          format: table
          exit-code: '1'
          severity: HIGH,CRITICAL

      - name: Run container
        run: |
          docker run -d \
            --name estudo-supabase-api \
            -p 3000:3000 \
            -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            -e SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
            estudo-supabase:latest

      - name: Wait for container health
        run: |
          for i in {1..10}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' estudo-supabase-api)
            echo "Health: $STATUS"

            if [ "$STATUS" = "healthy" ]; then
              exit 0
            fi

            if [ "$STATUS" = "unhealthy" ]; then
              docker logs estudo-supabase-api
              exit 1
            fi

            sleep 5
          done

          docker logs estudo-supabase-api
          exit 1

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag estudo-supabase:latest ghcr.io/derickcarmelo0248/estudo-supabase:latest

      - name: Push Docker image
        run: docker push ghcr.io/derickcarmelo0248/estudo-supabase:latest

      - name: Check Node.js version
        run: node --version

      - name: Check project
        working-directory: app
        run: node --check index.js
